---
- name: Converge
  hosts: all
  pre_tasks:
    - name: All ansible hostname to sensu_masters group
      add_host:
        name: "{{ item }}"
        groups: sensu_masters
      loop: "{{ ansible_play_hosts }}"
      changed_when: false

    - name: Ensure container hostnames are correct
      hostname:
        name: "{{ inventory_hostname }}"
      when: inventory_hostname != 'amazonlinux-1'

    - block:

      - name: Install apt packages for SNI fix
        package:
          name:
            - python-pip
            - python-dev
            - python-urllib3
            - python-openssl
            - python-pyasn1

      - name: Install Python packages for SNI fix
        pip:
          name:
            - ndg-httpsclient

      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_python_version is version_compare('2.7.9', '<')

  roles:
    - role: sensu-ansible
