---
# tasks/SmartOS/redis.yml: Deploy redis
# Specific to Ubuntu

- name: Include ansible_distribution vars
  include_vars: "{{ ansible_distribution }}.yml"
  tags: redis

- name: Ensure redis is installed
  tags: redis
  pkgin: name=redis state={{ redis_pkg_state }}
