---
# tasks/SmartOS/redis.yml: Deploy redis
# Specific to Ubuntu

- include_vars: "{{ ansible_distribution }}.yml"
  tags: redis

- name: Ensure redis is installed
  tags: redis
  pkgin: name=redis state={{ redis_pkg_state }}
