---
scenario:
  name: amazonlinux
platforms:
  - name: amazonlinux-1
    image: dokken/amazonlinux
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    groups:
      - sensu_checks
  - name: amazonlinux-2
    image: dokken/amazonlinux-2
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    groups:
      - sensu_checks
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  inventory:
    host_vars:
      amazonlinux-1:
        inspec_version: el6
      amazonlinux-2:
        inspec_version: el7
