---
scenario:
  name: oraclelinux
platforms:
  - name: oraclelinux-7
    image: dokken/oraclelinux-7
    command: /usr/lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    groups:
      - sensu_checks
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  inventory:
    host_vars:
      oraclelinux-7:
        inspec_version: el7
