---
scenario:
  name: debian
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: debian-8
    image: dokken/debian-8
    command: /lib/systemd/systemd
    privileged: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-9
    image: dokken/debian-9
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: timer,profile_tasks
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      poll_interval: 3
      forks: 100
    connection:
      pipelining: true
  playbooks:
    prepare: ../shared/prepare.yml
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
    converge: ../shared/playbook.yml
    verify: ../shared/verify.yml
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        sensu_master: true
        sensu_include_dashboard: true
        sensu_rabbitmq_server: true
        sensu_redis_server: true
        sensu_rabbitmq_host: "{{ ansible_hostname }}"
        sensu_redis_host: "{{ ansible_hostname }}"
        sensu_api_host: "{{ ansible_hostname }}"
        ansible_default_ipv4:
          address: 127.0.0.1
    host_vars:
      debian-8:
        inspec_version: ubuntu1604
      debian-9:
        inspec_version: ubuntu1604
verifier:
  name: inspec
  directory: ../shared/
  lint:
    name: rubocop
